### ISSUE TITLE
accountNumber passed to partialpath where change should be used

### ISSUE THREAD

**Issue by zanepocock** [swan-bitcoin/xpub-tool#43]
In `xpub-lib/src/derivation.js` the `accountNumber` passed in by the user is being used to derive addresses from the `change` segment of the derivation path. See here:

https://github.com/swan-bitcoin/xpub-tool/blob/0c2cd9f090665f8eb23c935fed28837488444e03/packages/xpub-lib/src/derivation.js#L97

In practice, this might just be a semantics issue, but for clarity's sake it should probably take `change` (0 or 1) as an input parameter.

It follows that the returned path when passing in an `accountNumber` of 1 (e.g. `path: "m/84'/0'/1'/0/0"`) would appear to be incorrect. Really we are returning the address at `path: "m/84'/0'/1'/1/0"`

**Comment by landabaso** [comment]
I think the change parameter should probably be validated against addressFromExtPubKey as well.

There's something I still don't understand though.
I see you kept the accountNumber as a parameter.

But isn't the accountNumber usually already encoded in the xpub?

4 bytes version | 1 byte depth | 4 bytes fingerprint | 4 bytes child number

The ledger nano will set depth to 3 and the child number will be set to the account number (setting the most significant bit to 1 since it's hardened).

So what does your tool do? Will it overwrite the 4 bytes of child number with whatever the user sets as accountNumber?
Since 0 is the default number, won't this break derivations very badly if not being extra careful?

BTW, are you planning to update npm with this change?

**Comment by zanepocock** [comment]
Thanks for the feedback @landabaso !

I agree with your observation about the account number being redundant and the linked PR intends to treat it as such. I just left it in because, since we return the full path, it might be useful for the sake of documentation? If the user knows they're passing in the xpub for account 3, for example, they might have a reason to want this tool to return `path: "m/84'/0'/3'/1/0"`, even if it doesn't change the derived addresses. But I will try to look into your suggestion over the weekend.

Pending internal review, if the linked PR is merged then yes I would expect we will update the npm package.

**Comment by zanepocock** [comment]
@landabaso if you feel like taking another look at the PR, I implemented your suggestion to derive the account number from the xpub. It was a great idea, I would be curious for your feedback.

**Comment by landabaso** [comment]
I took a look at it. Have you considered getting the depth and making sure it is == 3?


```
function getAccountFromExtPubKey(extPubKey) {
  const rawAccountNumber = getExtPubKeyMetadata(extPubKey).index

  //Something like this->
  assert(getExtPubKeyMetadata(extPubKey).depth === 3)


  if (rawAccountNumber > 2147483647) {
    return rawAccountNumber - 2147483648
  }
  return rawAccountNumber
}
```

Of course, this will only work with derivations using standard paths. Old electrum paths were not following this. Also, I believe that Bitcoin Core also use different derivation paths. But Trezor, Ledger and other should be fine.
